default-network = "esmeralda"

[networks.localnet]
wallet-daemon-url = "http://127.0.0.1:5100/json_rpc"
metadata-server-url = "http://localhost:3000/"

[networks.esmeralda]
wallet-daemon-url = "http://127.0.0.1:5100/json_rpc"
template-address = "template_0e86bea910ee33e3fc8da6ede2eaf4c16aae6a1dee7d8ab8408756b9af8d7e1d"
